### ISSUE TITLE
Parserbibliothek

### ISSUE THREAD

**Issue by jvoigtlaender** [SimonDieck/Deskriptive-Programmierung-Projekt#1]
Vermutlich sollten Sie statt der naiven Bibliothek aus der Vorlesung eine reifere Bibliothek nehmen, mit mehr Ausdrucksstärke durch weitere Kombinatoren (z.B. `lookAhead`), und besserer Fehlerbehandlung.

In Frage kämen m.E.:
- https://hackage.haskell.org/package/parsec
- https://hackage.haskell.org/package/megaparsec

**Comment by SimonDieck** [comment]
Werde mich über das Wochenende in die von ihnen vorgeschlagenen Bibliotheken einlesen und damit arbeiten. Die ursprüngliche Idee, weswegen ich die Bibliotheken aus der Vorlesung verwendet habe war, dass ich während der Klausur keine Notationen durcheinander bringen wollte.

**Comment by jvoigtlaender** [comment]
> ... dass ich während der Klausur keine Notationen durcheinander bringen wollte.

Das kann bei der Korrektur ja gegebenenfalls berücksichtigt werden.

Sollte die Entscheidung hier im Projekt nicht (in die eine oder andere Richtung) beeinflussen.
