### ISSUE TITLE
Anwendung von hlint?

### ISSUE THREAD

**Issue by jvoigtlaender** [SimonDieck/Deskriptive-Programmierung-Projekt#3]

**Comment by SimonDieck** [comment]
Nachdem ich den Großteil dieser Woche mit einer Sommergrippe krank war bin ich derzeitig mit dem Projekt etwas arg unter Zeitdruck. Ich werde mich bemühen den Code so weit es die Zeit erlaubt aufzuräumen und zu verschönern. Dazu gehört auch die Verwendung von hlint, derzeitige Priorität ist jedoch die Funktionalität in der gegebenen Zeit zu gewährleisten.
